name: Zig Builder
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  Zig-Latest-Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ca-certificates apt-utils lsb-release
      - name: Copy llvm source list
        run: |
          sudo cp ${{ github.workspace }}/llvm.source.list /etc/apt/sources.list.d/llvm.source.list
      - run: sudo apt-get update -y
      - run: sudo apt-get dist-upgrade -y
      - run: sudo apt install -y git build-essential cmake llvm-15 llvm-15-dev lld lld-15 liblld-15-dev clang-15 libclang-15-dev zlib1g-dev
      - uses: actions/checkout@master
        with:
          repository: ziglang/zig
          path: zig
          ref: master
      - name: Make build directory under zig
        run: mkdir ${{ github.workspace }}/zig/build
      - name: Run cmake
        working-directory: ${{ github.workspace }}/zig/build
        run: cmake ..
      - name: Creating swapfile / Use swap
        run: |
          sudo fallocate -l 4GB /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
      - name: Make install
        working-directory: ${{ github.workspace }}/zig/build
        run: make install
      - name: Get built zig version
        run: echo '::set-output name=ZIG_VER::$(${{ github.workspace }}/zig/build/stage3/bin/zig version)'
        id: zig_ver

      - name: zig_ver
        run: echo "${{ steps.zig_ver.outputs.ZIG_VER }}"

      - name: Make zig release directory
        run: mkdir -p ${{ github.workspace }}/zig-"${{ steps.zig_ver.outputs.ZIG_VER }}"

      - name: Copy results into release directory (bin)
        run: cp -pr ${{ github.workspace }}/zig/build/stage3/bin ${{ github.workspace }}/zig-"${{ steps.zig_ver.outputs.ZIG_VER }}"/

      - name: Copy results into release directory (lib)
        run: cp -pr ${{ github.workspace }}/zig/build/stage3/lib/zig/ ${{ github.workspace }}/zig-"${{ steps.zig_ver.outputs.ZIG_VER }}"/lib/

      - uses: actions/upload-artifact@v3
        with:
          name: zig-"${{ steps.zig_ver.outputs.ZIG_VER }}"
          path: ${{ github.workspace }}/zig-"${{ steps.zig_ver.outputs.ZIG_VER }}"
